"""tables

Revision ID: d2a900fd1fd3
Revises: 
Create Date: 2020-05-16 03:35:23.295430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a900fd1fd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('localisation', sa.String(length=140), nullable=True),
    sa.Column('job', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=140), nullable=True),
    sa.Column('size', sa.String(length=140), nullable=True),
    sa.Column('hash', sa.String(length=140), nullable=True),
    sa.Column('date', sa.String(length=140), nullable=True),
    sa.Column('counter', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    op.drop_table('user')
    # ### end Alembic commands ###
